version: "3"
services:
  weblate:
    image: pinkuburu/webtest
    tmpfs:
      - /app/cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
      - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: web
  weblate-celery-backup:
    image: pinkuburu/webtest
    tmpfs:
      - /app/cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
    environment:
      WEBLATE_SERVICE: celery-backup
  weblate-celery-beat:
    image: pinkuburu/webtest
    tmpfs:
      - /app/cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
    environment:
      WEBLATE_SERVICE: celery-beat
  weblate-celery-celery:
    image: pinkuburu/webtest
    tmpfs:
      - /app/cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
      - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: celery-celery
  weblate-celery-memory:
    image: pinkuburu/webtest
    tmpfs:
      - /app/cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
      - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: celery-memory
  weblate-celery-notify:
    image: pinkuburu/webtest
    tmpfs:
      - /app/cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
      - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: celery-notify
  weblate-celery-translate:
    image: pinkuburu/webtest
    tmpfs:
      - /app/cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
      - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: celery-translate
  database:
    image: postgres:13-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:6-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
